name: Deploy snowfall-generator to Beget

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '23'

            - name: Cache Node.js modules
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

            - name: Generate Config
              env:
                  API_URL: ${{ secrets.API_URL }}
              run: node generateConfig.js

            - name: SFTP Deploy
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: yuriypvh.beget.tech
                  username: ${{ secrets.SSH_USER }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  protocol: ftps
                  local-dir: ./
                  exclude: |
                      **/.git*
                      **/node_modules/**
                      **/src/**
                      **/package.json
                      **/package-lock.json
                      **/gulpfile.js
                      **/generateApiKeys.js
                      **/README.md
